const DATA = [
  {
    id: "0",
    name: "Pet Pooja",
    rating: "*****",
    description:
      "We make the most delicious authentic odia food.We make the most delicious authentic odia food",
    location: "Acharya Vihar",
    items: [
      {
        id: "0",
        title: "French Burger",
        description: "2 veg burgers with sause",
        image: "",
        cost: 130,
        quantity: 0,
        incart: false,
      },
      {
        id: "1",
        title: "Mushroom Thali",
        description: "Pure Veg thali with mushroom and sabji,rice",
        image: "",
        cost: 180,
        quantity: 0,
        incart: false,
      },
      {
        id: "2",
        title: "French Burger",
        description: "2 veg burgers with sause",
        image: "",
        cost: 130,
        quantity: 0,
        incart: false,
      },
      {
        id: "3",
        title: "Mushroom Thali",
        description: "Pure Veg thali with mushroom and sabji,rice",
        image: "",
        cost: 180,
        quantity: 0,
        incart: false,
      },
    ],
  },
  {
    id: "1",
    name: "Hotel Priya",
    rating: "***",
    description:
      "We make the most delicious authentic odia food.We make the most delicious authentic odia food",
    location: "Acharya Vihar",
    items: [
      {
        id: "0",
        title: "French Burger",
        description: "2 veg burgers with sause",
        image: "",
        cost: 130,
        quantity: 0,
        incart: false,
      },
      {
        id: "1",
        title: "Mushroom Thali",
        description: "Pure Veg thali with mushroom and sabji,rice",
        image: "",
        cost: 180,
        quantity: 0,
        incart: false,
      },
      {
        id: "2",
        title: "French Burger",
        description: "2 veg burgers with sause",
        image: "",
        cost: 130,
        quantity: 0,
        incart: false,
      },
      {
        id: "3",
        title: "Mushroom Thali",
        description: "Pure Veg thali with mushroom and sabji,rice",
        image: "",
        cost: 180,
        quantity: 0,
        incart: false,
      },
    ],
  },
  {
    id: "2",
    name: "Jyoti's Kitchen",
    rating: "****",
    description:
      "We make the most delicious authentic odia food.We make the most delicious authentic odia food",
    location: "Acharya Vihar",
    items: [
      {
        title: "French Burger",
        description: "2 veg burgers with sause",
        image: "",
        cost: 130,
        quantity: 0,
        incart: false,
      },
      {
        title: "Mushroom Thali",
        description: "Pure Veg thali with mushroom and sabji,rice",
        image: "",
        cost: 180,
        quantity: 0,
        incart: false,
      },
    ],
  },
  {
    id: "3",
    name: "Kg By Biryani",
    rating: "****",
    description: "Biryani by KG famous for it's biryani served based on KG.",
    location: "Acharya Vihar",
    items: [
      {
        title: "French Burger",
        description: "2 veg burgers with sause",
        image: "",
        cost: 130,
        quantity: 0,
        incart: false,
      },
      {
        title: "Mushroom Thali",
        description: "Pure Veg thali with mushroom and sabji,rice",
        image: "",
        cost: 180,
        quantity: 0,
        incart: false,
      },
    ],
  },
];

export default DATA;
